version: '3'
services:

  ### Services ###
  discovery-server:
    image: 'aenesgur/ms-ex/discovery-server-image'
    container_name: discovery-server
    build:
      context: ./discovery-server/
    ports:
      - "8761:8761"

  api-gateway:
    image: 'aenesgur/ms-ex/api-gateway-image'
    container_name: api-gateway
    build:
      context: ./api-gateway/
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
    ports:
      - "4040:8080"
    expose:
      - "4040"
    depends_on:
      - discovery-server

  product-service:
    container_name: product-service
    image: 'aenesgur/ms-ex/product-service-image'
    build:
      context: ./product-service/
    ports:
      - "4041:4041"
    environment:
      - server.port=4041
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-productservice:5431/product-service
      - SPRING_DATASOURCE_USERNAME=productservice-user
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka

    depends_on:
      - postgres-productservice
      - discovery-server

  order-service:
    image: 'aenesgur/ms-ex/order-service-image'
    container_name: order-service
    build:
      context: ./order-service/
    environment:
      - server.port=4042
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysql-orderservice:3307/order-service?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=123456
      - spring.jpa.hibernate.ddl-auto=update
    ports:
      - "4042:4042"
    expose:
      - "4042"
    depends_on:
      - discovery-server
      - mysql-orderservice

  product-stock-service:
    image: 'aenesgur/ms-ex/product-stock-service'
    container_name: product-stock-service
    build:
      context: ./product-stock-service/
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
    ports:
      - "4043:4043"
    expose:
      - "4043"
    depends_on:
      - discovery-server

  send-sms-service:
    image: 'aenesgur/ms-ex/send-sms-service'
    container_name: send-sms-service
    build:
      context: ./send-sms-service/
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
    ports:
      - "4044:4044"
    expose:
      - "4044"
    depends_on:
      - discovery-server


  ### Dependencies ###
  postgres-productservice:
    container_name: postgres-productservice
    image: postgres
    environment:
      POSTGRES_DB: product-service
      POSTGRES_USER: productservice-user
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - ./postgres-productservice:/data/postgres
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    restart: unless-stopped

  mysql-orderservice:
    container_name: mysql-orderservice
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=order-service
      - MYSQL_TCP_PORT=3307
    expose:
      - "3307"
    ports:
      - "3307:3307"
    volumes:
      - ./mysql-orderservice:/data/mysql






